spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flyway?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  flyway:
    # \u914D\u7F6E\u542F\u52A8\u626B\u63CF
    enabled: true
    # \u914D\u7F6E\u57FA\u7EBF
    baseline-on-migrate: true
server:
  port: 8080